// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Ip        *netip.Addr
	Username  string
	CreatedAt pgtype.Timestamptz
}
