// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: utility.sql

package db

import (
	"context"
)

const pingVersion = `-- name: PingVersion :one
SELECT version()
`

func (q *Queries) PingVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, pingVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
